### ISSUE TITLE
まわせるポイント

### ISSUE THREAD

**Issue by udonka** [udonka/neominlette#16]

**Comment by udonka** [comment]
![2015-02-08_02h23_42](https://cloud.githubusercontent.com/assets/4636305/6092983/9305e80a-af39-11e4-96df-48b73c33605a.png)

MPウィンドウなるものを左上に追加した。
現在入っているユーザーとそのMPを表示している。

**Comment by udonka** [comment]
MPをどこにもっているかというと、サーバー上のsocketオブジェクトの中。
Javascriptではどんなオブジェクトにも追加でプロパティを設定していいので、socket.mpというのを追加した。

socketオブジェクトは、サーバーサイドからみたクライアントとのコネクションを表している。
つまり、ルーレットのユーザーそのものというわけだ。なので、ここに保存することにした。

**Comment by udonka** [comment]
まわせるポイント追加機能もつけた。完成。

**Comment by hayate-** [comment]
お疲れ様！割り当て分やれてなくてすまん。
回せるポイントの表示、四角より丸の方が可愛らしくて、ルーレットとの統一感も出るかなと思ったけれども、どうだろう？あと、どのポイントが自分のポイントなのか、もっとぱっと見でわかるほうがいいかな。(現在だと、四角が少し大きいやつかな？)
