### ISSUE TITLE
アニメーションをフリーハンド(スプライト曲線)にする

### ISSUE THREAD

**Issue by udonka** [udonka/neominlette#32]
現在は直線だが。軌跡を表示

**Comment by udonka** [comment]
どういう実装にしたんですか？？

**Comment by hayate-** [comment]
pointerdown&&pointermove のときに、pointermoveが発生するたびにx,y座標を配列に記憶、
pointerupが発生した時にPaper.pathメソッドでx,y座標の配列を制御点としたCatmull-Rom曲線を書いています。
制御点を多くしすぎると線がガタガタになってしまうので、ある程度制御点が集まったらあえて描画に使う制御点を減らしてます。(これがベストな方法かはわからない)

**Comment by udonka** [comment]
なるほど。 Catmull-Rom曲線のチョイスはたぶんベストだね！
制御点を減らすのも、妥当だと思う！

ただ、pointはどうせ捨てるなら、リアルタイムに捨てちゃえばいいのかなとも思った。

count = (count + 1 ) % freq; // freq 回ごとにcountが0に戻る
if(count == 0)
  arrowPoints.push(point)

みたいな？

でも、このIssueは一旦クローズしよ
