### ISSUE TITLE
フリックの軌跡、ただの線じゃなくて、矢印にする

### ISSUE THREAD

**Issue by udonka** [udonka/neominlette#34]
向きがわからない

**Comment by udonka** [comment]
すすんでそうだね。どうやって実現したのか気になる。

**Comment by hayate-** [comment]
SVGでは線の始点・頂点・終点に好きな図形をmarkerとして配置できるので、三角形をmarkerとして終点につけたよ。

**Comment by udonka** [comment]
markerか！そんな機能があったとは！
いいんじゃないでしょうか。

矢印つけてちょっと図形が複雑になったから、フェードアウトで消えるスピードもっと早くてもいいかもね。

大体OKなのでいったんクローズ。

つぎ、やりたいことなければ　#36 あたりやってもらえる？

**Comment by hayate-** [comment]
了解！
