### ISSUE TITLE
ルーレットグループ名を表示

### ISSUE THREAD

**Issue by udonka** [udonka/neominlette#36]

**Comment by udonka** [comment]
はやくして

**Comment by udonka** [comment]
@hayate- はやてくーん

**Comment by udonka** [comment]
@hayate- おーい

**Comment by udonka** [comment]
今、ルーレットグループ名は、ルーレット一覧画面でしか見れないのでほとんど意味がない。
ルーレットプレイ画面で、表示されるようにしてほしい。

工程としては、routesで渡してあげて、viewsで表示するような感じになるだろう。

blanding画面を参考にすればいいと思う。

**Comment by hayate-** [comment]
解決したんでクローズしますねん

**Comment by udonka** [comment]
やったね
